### ISSUE TITLE
Black icons with DBM

### ISSUE THREAD

**Issue by stokbaek** [solor/FreeUI.Fluffy#2]
Seems like some skinning issues with freeUI and dbm.

![image](https://cloud.githubusercontent.com/assets/5165133/21526997/8351705a-cd28-11e6-8cc2-4db380f75c3d.png)

**Comment by solor** [comment]
Works fine on my end, do you have any other addon affect this part?

**Comment by stokbaek** [comment]
Looks like it was some leftover settings in the saved vars in dbm on my part.
